"""Version identifiers recorded by CQRP research and execution events."""

PLATFORM_VERSION = "2.0.0-dev"
COA_ENGINE_VERSION = "1.0.0-baseline"
VALIDATION_ENGINE_VERSION = "1.0.0"
SIGNAL_ENGINE_VERSION = "1.0.0"
PAPER_EXECUTION_VERSION = "1.0.0"
PORTFOLIO_RISK_VERSION = "1.0.0"
ANALYTICS_ENGINE_VERSION = "1.0.0"
LIVE_EXECUTION_VERSION = "1.0.0"
RESEARCH_SCHEMA_VERSION = 9
